# Generated by Django 3.0.8 on 2020-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_created_at_updated_at_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessright',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
