# Generated by Django 3.1.1 on 2020-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccess',
            fields=[
                ('api_name', models.CharField(max_length=50)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
    ]
